### ISSUE TITLE
Pedido de invalidação de aulas

### ISSUE THREAD

**Issue by DavidQBP7NW** [alicerce-lab/alicerce-lab#111]
Peço que a aula do dia 08/03 das turmas 2082 e 2083 sejam invalidadas
A líder acordou passando mal e não conseguiu ir ao polo. Não foi possível uma substituição
Além disso, o coordenador não conseguiu retirar o planejamento e invalidar a aula a tempo

**Comment by gmfc** [comment]
Aulas invalidadas
