### ISSUE TITLE
Data de validação de meta incorreta

### ISSUE THREAD

**Issue by DavidQBP7NW** [alicerce-lab/alicerce-lab#114]
As turmas 2184 e 2185 tiveram aplicação de MAPA na semana do dia 29/02/2024 e a líder validou as metas na mesma semana.
Porém o coordenador ao averiguar percebeu que alguns alunos estavam com metas definidas com a datas da semana do dia 11/03/2024 (IMAGEM 1)
IMAGEM 1 - 
![image](https://github.com/alicerce-lab/alicerce-lab/assets/150094501/a9dc8535-f9d3-4e68-96c1-169ea6426b24)

Tentei verificar mais afundo o que pode ter ocorrido pelo LMS e pelo DBeaver mas não identifiquei nada estranho
Gostaria de entender o que pode ter levado a fazer isso acontecer

**Comment by gianpietrolucio** [comment]
@DavidQBP7NW Aparentemente, considerando agora que foram definidas as metas no dia 14/03/2024, não foi possível identificar se houve um problema, pois as datas estão correspondendo corretamente com a aplicação e afins realizadas para a turma 2184 e 2185. Algumas metas foram definidas como "Aluno Sem Aplicação" como obs. do instrutor. 

Sabe informar se após essas metas ocorreu mais problemas relacionadas a essas questões?

**Comment by DavidQBP7NW** [comment]
Não ocorreu mais problemas relacionado a essa questão
