### ISSUE TITLE
Invalidar aulas com planejamento feito

### ISSUE THREAD

**Issue by DavidQBP7NW** [alicerce-lab/alicerce-lab#115]
As turmas:
1328 - SQS-M; 
1329 - SQS-T ;
1305 - SQS-T;
Não tiveram aula por conta da dengue. O planejamento já estava feito o que impossibilita a invalidação da aula pelo LMS
Podem invalidar, por favor?

**Comment by DavidQBP7NW** [comment]
A turma 1984 também precisa ter as aulas dos dias 12/03 e 14/03 invalidas, as aulas foram canceladas devido ao surto de dengue
A coordenadora disse que fez a invalidação mas as aulas voltaram

**Comment by gmfc** [comment]
@DavidQBP7NW 
turma 1984 aulas do dia 12/3 e 14/3
as turmas: 1328, 1329 e 1305 sao quais dias? e possivel listar os IDs das daily classes

**Comment by DavidQBP7NW** [comment]
Turmas 1328, 1329 e 1305 invalidar aula do dia 15/03
Dailyclasses ClassID
153756	1329
153681	1305
153696	1328

**Comment by gmfc** [comment]
Invalidadas:

153681
153696
153756
