### ISSUE TITLE
Problemas no Homolog

### ISSUE THREAD

**Issue by DavidQBP7NW** [alicerce-lab/alicerce-lab#123]
Pessoal do processo seletivo está sem conseguir acessar o ambiente de homolog, ao acessar a seguinte mensagem aparece "Permissão do sistema não encontradas" (IMAGEM 1)
Usei o e-mail lider163.fomacao@lideres.alicerceedu.com.br para teste e apareceu a mesma mensagem
O e-mail instrutor103.formacao@alicerceedu.com.br também está com esse problema
A coordenadora do processo seletivo disse que isso está ocorrendo com todos usados
IMAGEM 1 - 
![image](https://github.com/alicerce-lab/alicerce-lab/assets/150094501/f53176bf-4d5f-4ea9-a707-b9dbe6feb2f3)

Poderiam verificar, por favor?

**Comment by gmfc** [comment]
Deve estar corrigido
