### ISSUE TITLE
Problemas ao realizar MAPA de inglês

### ISSUE THREAD

**Issue by DavidQBP7NW** [alicerce-lab/alicerce-lab#126]
Os alunos da turma 1322 não estão conseguindo realizar o MAPA de inglês
Ao tentar realizar a prova uma mensagem de erro aparece na tela (IMAGEM 1)

IMAGEM 1 - 
![image](https://github.com/alicerce-lab/alicerce-lab/assets/150094501/30cc4e7a-f1f5-45a9-ad48-8054dafd752d)

Além disso o aluno Jaime Otavio Lima conseguiu fazer uma questão do MAPA e a mesma mensagem apareceu, agora consta como finalizado para o aluno mas ele não realizou a prova totalmente
A líder limpou cachê, atualizou a página e mesmo assim o erro continua

**Comment by gmfc** [comment]
@DavidQBP7NW nesse caso, precisa lancar novamente. Cancelamos as provas pendentes e em andamento da trilha antiga
