### ISSUE TITLE
Divergencia de resultado em aplicação de minimapa

### ISSUE THREAD

**Issue by DavidQBP7NW** [alicerce-lab/alicerce-lab#135]
Um CC apresentou divergência na última aplicação do minimapa de matemática nas turmas 1328/1330. Foi realizado uma aplicação de forma online, cujo a prova tinha que ser de DESB 4, e os resultados deram a nível de DESB 6. IMAGEM 1 
IMAGEM 1 - 
![image](https://github.com/alicerce-lab/alicerce-lab/assets/150094501/c1163a9d-ff92-4b37-a1db-eee7d0fe7dc9)

Na turma 1321. Em exemplo é o mapa  a Aldrin estava DESB6 e no minimapa de leitura passou pra MOCH1, sendo que o intervalo entre eles tá ficando tudo cinza IMAGEM 2

IMAGEM 2 - 
![image](https://github.com/alicerce-lab/alicerce-lab/assets/150094501/b57d54a1-2761-44bf-870b-fe9beea5685c)

**Comment by Jessica-Ribas** [comment]
Aqui aconteceu o mesmo problema porém sem nenhuma cor em nenhum campo. O aluno fez o mini mapa e teve a meta definida. A cor continuou cinza e a data da definição de meta não mudou.
Turma: 1952
Turma: 354
![image](https://github.com/alicerce-lab/alicerce-lab/assets/144057394/8195c79f-1c33-45fc-9c9c-a0c8d8d8d813)
![image](https://github.com/alicerce-lab/alicerce-lab/assets/144057394/435d5b7f-4932-4c3e-8a5d-3629a0cbc64a)


Turma: 1978
Foi definido a meta de alguns alunos, porém a data da definição não mudou e tambem as cores continuaram cinza, como se a meta não tivesse sido definida hoje.
![image](https://github.com/alicerce-lab/alicerce-lab/assets/144057394/75038f21-4021-4760-8f37-7ec251873220)

**Comment by Jessica-Ribas** [comment]
Não é possível definir a meta desses alunos, mesmo aplicando a prova e tentando definir a ultima definição não muda para o dia atual.
id alunos
38370
43320

**Comment by BrunoFilippini** [comment]
Hipótese: Possivelmente seja o start mockado

**Comment by Jessica-Ribas** [comment]
Na turma 1834 não esta aparecendo o botão para realizar a definição de metas em alguns alunos, mesmo a prova estando finalizada na semana vigente.
Segue o print:
![image](https://github.com/alicerce-lab/alicerce-lab/assets/144057394/a44255e8-e7d4-4780-8d2e-29b4da5995f0)

**Comment by Jessica-Ribas** [comment]
Turma 1978 esta com inconsistência nos blocos de definição de meta.
Exemplo 1: Aluna Luiza de Oliveira Stubert continua sem cor nos blocos
![image](https://github.com/alicerce-lab/alicerce-lab/assets/144057394/03457eb1-793c-46a9-ae2d-b8ae5e4b8ea3)
Exemplo 2 :Aluno Miguel Gonçalves de Souza esta com inconsistência nas cores, primeiro bloco do print esta como não dominado, segundo bloco sem cor.
![image](https://github.com/alicerce-lab/alicerce-lab/assets/144057394/6c7a5db3-eed3-4c1d-b17c-9142f039ab63)
@BrunoFilippini

**Comment by GabrielCampos99** [comment]
# Primeiro caso
Aluna: **Ana Laura**
lms student id: **39603**
Rota web: **https://lms.alicerceedu.com.br/lancador/minimapa/matematica/1328**

- A aluna  **Ana Laura**, ela teve um minimapa aplicado no dia **27/05/2024**, com o ID da aplicação **706453**, no qual as habilidades (skills) testadas foram do bloco **desb6**. Depois de validado a meta do aluno, podemos selecionar até 2 blocos a frente e será testados as habilidades daquele bloco, somente daquele bloco. No caso, foi lançado uma aplicação no bloco desb6 e foram testadas apenas as habilidades deste bloco. As outras anteriores não foram afetadas / testadas. Por esse motivo não foram **coloridas**

> Um CC apresentou divergência na última aplicação do minimapa de matemática nas turmas 1328/1330. Foi realizado uma aplicação de forma online, cujo a prova tinha que ser de DESB 4, e os resultados deram a nível de DESB 6. IMAGEM 1
IMAGEM 1 -

# Segundo caso
Aluna: **Aldrin**
lms student id: **44731**
Rota web: **https://lms.alicerceedu.com.br/lancador/minimapa/leitura/1321**

- Aqui a meta está sendo validada em bloco superiores a zdp. Quando lançamos o minimapa, ele poderá lançar a partir do bloco da meta validada. E o minimapa será testará apenas as habildiades (skills) do bloco escolhido antes de lanaçar o minimapa.

> Na turma 1321. Em exemplo é o mapa a Aldrin estava DESB6 e no minimapa de leitura passou pra MOCH1, sendo que o intervalo entre eles tá ficando tudo cinza IMAGEM 2

**Comment by GabrielCampos99** [comment]
@BrunoFilippini @DavidQBP7NW

**Comment by BrunoFilippini** [comment]
@DavidQBP7NW Issue respondida pelo Dev, é um caso de alinhamento com os lideres e CC para explicar o funcionamento
Issue encerrada.
