### ISSUE TITLE
Lider com Id trocado 

### ISSUE THREAD

**Issue by Lukproi** [alicerce-lab/alicerce-lab#15]
![image](https://github.com/alicerce-lab/alicerce-lab/assets/143440622/0caeebe6-f186-47d9-9181-1bdc40ac759f)
![image](https://github.com/alicerce-lab/alicerce-lab/assets/143440622/391b0e59-b33e-4028-bb23-6b7bdd86f02e)
![image](https://github.com/alicerce-lab/alicerce-lab/assets/143440622/0e9a190a-1278-460a-9b07-9902a29d6881)

**Comment by gmfc** [comment]
Lucas, qual Id esta trocado? e para trocar o lms_user em questao e o Thiago Ataide Silva, o usuario no DB mostrado e somente Thiago Silva. Pode esclarecer o problema?

**Comment by gmfc** [comment]
Resolvido
