### ISSUE TITLE
Planejamento criado para semana inteira na turma TQ

### ISSUE THREAD

**Issue by Jessica-Ribas** [alicerce-lab/alicerce-lab#22]
A turma 380 teve o planejamento criado para semana toda, porem os dias de aulas são somente terça e quinta, isso ocorreu pela troca de horário e dias incorretos, consegue excluir os dias que são diferentes de terça e quinta?
https://lms.alicerceedu.com.br/planejamento-aula/aulas/turma/380

**Comment by gmfc** [comment]
Duplicada de https://github.com/alicerce-lab/gip/issues/86 ?

**Comment by gmfc** [comment]
Duplicada

**Comment by Jessica-Ribas** [comment]
@gmfc essa é para exclusão de dias, vi aqui a que você marcou como duplicada é inclusão, e não é bug essa, foi por troca de horário e dias mesmo.
