### ISSUE TITLE
Planejamento sumiu do lms

### ISSUE THREAD

**Issue by Jessica-Ribas** [alicerce-lab/alicerce-lab#27]
Turma 380 Planejamentos das S1 e S2 sumiram do lms, mas lider havia feito.

https://lms.alicerceedu.com.br/planejamento-aula/aulas/turma/380
![image](https://github.com/alicerce-lab/alicerce-lab/assets/144057394/0e31850e-169f-4831-9c84-aa7c7a0281e4)

**Comment by FeTanaka** [comment]
@Jessica-Ribas, boa noite

poderia me dar mais detalhes sobre essa issue?
