### ISSUE TITLE
Reprovar lançamentos de horas em massa

### ISSUE THREAD

**Issue by vanderleyviana** [alicerce-lab/alicerce-lab#33]
É muito comum no fechamento do mês percebermos horas que foram lançadas incorretamente a aprovadas pelo coordenador. Nesses casos solicitamos o coordenador reprovar essas horas e solicitar ao líder que lance novamente. Porém quando o coordenador vai reprovar as horas não é possível selecionar várias horas de uma só vez e reprová-las. É necessário reprovar uma por uma tornando essa uma tarefa repetitiva e cansativa.

Minha sugestão é que seja possível selecionar vários lançamentos e reprová-los em massa.

**Comment by gmfc** [comment]
PB nao permite fazer uma operacao dessa em massa. @gianpietrolucio e @oleonardofernandes estao desenhando uma saida diferente
