### ISSUE TITLE
Dois LMS_ID para um USER_ID

### ISSUE THREAD

**Issue by DavidQBP7NW** [alicerce-lab/alicerce-lab#45]
Existe dois LMS_ID para um USER_ID
1303 Camila de Carvalho Marcondes, user_ID 1426
1398 Camila Carvalho Marcondes, user_ID 1426

Ambas com user_ID 1426, por gentileza, apaguem o 1304 (Camila DE Carvalho Marcondes)
OBS - Peço urgência pois essa questão está interferindo no fechamento financeiro

**Comment by gmfc** [comment]
voce pediu a para deletar o lms_user 1304, assumo que esteja falando do 1303. Feito

![image](https://github.com/alicerce-lab/alicerce-lab/assets/4379465/afea2d6a-8359-4d85-b768-a480cb0a6f73)
