### ISSUE TITLE
Excluir sprint criada pelo coordenador

### ISSUE THREAD

**Issue by Jessica-Ribas** [alicerce-lab/alicerce-lab#46]
Solicito e exclusão das sprints criadas pelo coordenador nas seguintes turmas.
1895
1896
1897
1898

**Comment by gmfc** [comment]
@Jessica-Ribas seria desinscrever essas turmas das agendas do coletivo?

![image](https://github.com/alicerce-lab/alicerce-lab/assets/4379465/f12a76a7-c2f1-414e-8482-2d9983602ab0)

**Comment by gmfc** [comment]
![image](https://github.com/alicerce-lab/alicerce-lab/assets/4379465/69711753-49a1-4ac9-ae63-bcfcfa60e88a)

ha uma agenda "teste" nessa turma. Seria para deletar essa agenda local?

**Comment by Jessica-Ribas** [comment]
Isso, deletar todas as agendas criadas com sprint. @gmfc, a turma vai ficar somente na agenda geral do alicerce

**Comment by gmfc** [comment]
@mr-danilo @gianpietrolucio preciso de um help aqui para saber se posso mesmo deletar essas sprints sem causar um caos no sistema

**Comment by gianpietrolucio** [comment]
> [@mr-danilo](https://github.com/mr-danilo) [@gianpietrolucio](https://github.com/gianpietrolucio) preciso de um help aqui para saber se posso mesmo deletar essas sprints sem causar um caos no sistema

Ao meu ver sim, Tem um projeto de meu conhecimento que tem uma Sprint cadastrada no sistema e criada através do ID -1 do Alicerce. Mas que está no seu fim para o dia 21/03/2024 esse projeto se encerra. (CMDCA se não me engano)

As Sprints que não são oriundas da criação sistêmica pelo @mr-danilo como a criação da Sprint 1.24 para a turma 2134 e associadas, não faz sentido existirem. 

Vejo só que algumas pessoas não sabem como associar a Sprint Alicerce como agenda externa e acabam criando uma interna para associar a geral com as datas iguais constam na Agenda Google. Seria bom implementar a Nova Agenda de uma vez para evitar situações como essas e deliberar somente uma Sprint como a ser seguida. A "Agenda Geral".

**Comment by gianpietrolucio** [comment]
@gmfc Falando com @Jessica-Ribas hoje na semanal, esse problema já foi resolvido láno ano passado. Essa issue é  antiga. Mas toda e qualquer Sprint que tiver que não foi criada pelo @mr-danilo, pode excluir.
