### ISSUE TITLE
Invalidar aulas com chamada feita

### ISSUE THREAD

**Issue by DavidQBP7NW** [alicerce-lab/alicerce-lab#58]
O líder da turma 913 fez chamada para a turma mesmo não tendo aula no dia 22/11 (quarta-feira)
A chamada foi realizada pois ele achou que o fato de não ter aula afetaria o indicador
OBS - A chamada foi feita, mas sem colocar presença para aluno
Por favor, invalide a aula, pois o coordenador não consegue invalidar

**Comment by gmfc** [comment]
Necessario desenhar escopo aqui. @gianpietrolucio precisamos ver todos os casos validos de invalidacao de aulas.

**Comment by gianpietrolucio** [comment]
Associação com issue: https://github.com/alicerce-lab/gip/issues/177

Em andamento.

**Comment by gianpietrolucio** [comment]
Após o deploy realizado ontem é possível realizar a invalidação das aulas. @DavidQBP7NW todas as issues que foram abertas para invalidação de aula podem ser dadas como concluídas? As aulas podem ser invalidadas agora. pelos próprios CCs
