### ISSUE TITLE
GIP | Problema com redirecionamento/acesso direto a links de atividades planejadas

### ISSUE THREAD

**Issue by gianpietrolucio** [alicerce-lab/alicerce-lab#62]
**Descreva o erro**
Aparentemente todas os links de planejamento não são acessíveis se clica-se no texto do link, somente um pouco abaixo na barra em que o link se encontra. O texto do link é copiável, mas não redireciona para acessar o link em si. 

**Para reproduzir**
Passos para reproduzir o comportamento:
1. Vá para 'Qualquer Planejamento de Aula, de qualquer turma'
2. Clique em 'Escolher uma atividade'
3. Clique em 'Criar ou Clonar uma atividade'
4. Insira um Link qualquer nessa atividade;
5. Adicione a atividade na Bandeja;
6. Adicione essa atividade da bandeja no Calendário do planejador de aula;
7. Clique no texto do link;
8. Agora clique um pouco abaixo do texto;
10. Veja o erro.

**Comportamento esperado**
Clicar no texto do link permite não somente a possibilidade de copiar o texto, mas redirecionar numa nova aba do navegador

**Desktop (por favor, preencha as seguintes informações):**
 - SO: [W10]
 - Navegador [Edge]

**Contexto adicional**
Report de CC direto do formulário de chamados das Nações:
 
 Nação: Nação B2B
 Coletivo: COL-B2B-QUA-C02
 Solicitante: Coordenador Eron Pereira
 Artefato: LMS
 
 Objetivo: Relatar um problema
 
 Sugestão: 
O que tentava fazer: Abrir o link inserido no planejamento
Ocorrência: Ao tentar clicar no link do planejamento, só é possível abrir o link diretamente clicando em um local específico da caixa de texto(logo abaixo do texto). Se clicar no texto, ele habilita copiar, mas para abrir diretamente o link, é necessário clicar em um ponto específico.

Bug acontece em todas as atividades planejadas com link

**Comment by FeTanaka** [comment]
https://gitlab.com/alicerce-lab/lms/lms-frontend/-/merge_requests/246
