### ISSUE TITLE
Alunos duplicando na chamada

### ISSUE THREAD

**Issue by Jessica-Ribas** [alicerce-lab/alicerce-lab#72]
Possuimos algumas turmas onde os alunos estão duplicando em alguns dias na chamada. 
Exemplo: id_turma 692
3 alunos estão duplicados na chamada no dia 18/12/2023
link turma: https://lms.alicerceedu.com.br/presencas/692/criar/retroativa

![image](https://github.com/alicerce-lab/alicerce-lab/assets/144057394/c8fed2bc-c8c9-4576-b910-f11dc0186583)

![image](https://github.com/alicerce-lab/alicerce-lab/assets/144057394/d0c65ee5-8f34-4b71-8861-463c17a29b10)

![image](https://github.com/alicerce-lab/alicerce-lab/assets/144057394/354cb6e1-4049-4c6e-81cb-33e3bf60b553)

Exemplo2: id_turma: 1774
3 alunos estão duplicados na chamada no dia 18/12/2023
Link turma:https://lms.alicerceedu.com.br/presencas/1774/criar/retroativa

![image](https://github.com/alicerce-lab/alicerce-lab/assets/144057394/ce912be2-0777-4560-acd3-2a37bbd40431)

![image](https://github.com/alicerce-lab/alicerce-lab/assets/144057394/0739a04c-f714-47a2-965b-4d47fe876a5a)

![image](https://github.com/alicerce-lab/alicerce-lab/assets/144057394/1cdf7008-fd96-407e-aac2-703bad369d1f)

**Comment by gianpietrolucio** [comment]
Associado a https://github.com/alicerce-lab/gip/issues/156 e alicerce-lab/gip#149

**Comment by gmfc** [comment]
Possivel duplicata de https://github.com/alicerce-lab/gip/issues/149

Sera fechada
