### ISSUE TITLE
Erro ao criar alunos

### ISSUE THREAD

**Issue by gomeespedro** [alicerce-lab/alicerce-lab#77]
**Descreva o erro**
Ao tentar criar alunos via LMS, na hora de salvar, aparece um erro na página, impossibilitando a criação. Vários CC's estão reportando esse mesmo erro.

**Para reproduzir**
Passos para reproduzir o comportamento:
1. Vá para diretório>aluno>criar
2. Clique em salvar
3. Veja o erro

**Capturas de tela**
![image](https://github.com/alicerce-lab/alicerce-lab/assets/150803548/f5562428-bec4-4214-bae4-51e297b50f69)

![image](https://github.com/alicerce-lab/alicerce-lab/assets/150803548/59347f4c-762b-483e-aa5c-2f7e03d0076b)

https://web.telegram.org/k/stream/%7B%22dcId%22%3A1%2C%22location%22%3A%7B%22_%22%3A%22inputDocumentFileLocation%22%2C%22id%22%3A%224906690386933581485%22%2C%22access_hash%22%3A%222149575396449812250%22%2C%22file_reference%22%3A%5B1%2C0%2C0%2C67%2C143%2C101%2C166%2C208%2C236%2C161%2C52%2C72%2C196%2C95%2C176%2C41%2C22%2C207%2C5%2C157%2C207%2C31%2C176%2C224%2C81%5D%7D%2C%22size%22%3A14859663%2C%22mimeType%22%3A%22video%2Fmp4%22%2C%22fileName%22%3A%22LMS%20Alicerce%20-%20Google%20Chrome%202023-12-20%2011-03-31.mp4%22%7D

![image](https://github.com/alicerce-lab/alicerce-lab/assets/150803548/2798ae17-52a9-4426-95b2-42630eaa9b43)

**Contexto adicional**
Adicione qualquer outro contexto sobre o problema aqui.

**Comment by gianpietrolucio** [comment]
Associado a: https://github.com/alicerce-lab/gip/issues/148

**Comment by gmfc** [comment]
Fechando duplicada
