### ISSUE TITLE
Coordenador não consegue editar horário de aula já criada

### ISSUE THREAD

**Issue by DavidQBP7NW** [alicerce-lab/alicerce-lab#97]
Coordenador do I02 criou uma aula para quinta-feira (15/02) com horário errado (01:00 até 23:59) na turma 2099
Ela e nem eu conseguimos editar o horário da turma
Seria melhor invalidar a aula e criar outra ou o coordenador deveria conseguir editar o horário de uma aula criada que ainda não ocorreu?

IMAGEM 1 -
![image](https://github.com/alicerce-lab/alicerce-lab/assets/150094501/a21cbff9-f435-497b-8c57-9d6b62897b77)

**Comment by gmfc** [comment]
Invalidar e recriar aula
